name: Push Events

on: 
  push:
    branches:
      - main
      - test # Triggers the workflow on push to the main branch

jobs:
  show-info:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Command
        run: echo "A new commit has been pushed!"
