name: manual workflow

on: 
  workflow_dispatch:
   
jobs:
  run-manual-task:
    runs-on: ubuntu-latest

    steps:
        uses: actions/checkout@v4
      - name: Echo Command
        run: echo "A new commit has been pushed!"
