name: Manual Workflow with Inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'  # A description of the input
        required: true  # Whether the input is required
        default: 'staging'  # Default value if none is provided
        type: string  # Type of the input (string in this case)
      version:
        description: 'Version of the application'
        required: false
        default: '1.0.0'
        type: string

jobs:
  run-manual-task:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Echo Environment
        run: echo "Deploying to the ${{ github.event.inputs.environment }} environment"

      - name: Echo Version
        run: echo "Deploying version ${{ github.event.inputs.version }}"
