name: Issue Opened Workflow

on: 
  issues:
    types:
      - opened  # Triggers the workflow when an issue is opened

jobs:
  run-issue-task:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4  # This checks out the repository code

      - name: Echo Command
        run: echo "An issue has been opened!"
