name: Manual Workflow

on: 
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-manual-task:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4  # This checks out the repository code

      - name: Echo Command
        run: echo "This is a manually triggered workflow!"
